### ISSUE TITLE
🐛 BUG: Selecting all units and files of a course doesn't select files

### ISSUE THREAD

**Issue by armel22** [h-da/geli#563] opened 2018-04-06 12:09 UTC
![screenshot_20180406_134726](https://user-images.githubusercontent.com/15012321/38420458-11b2faba-39a4-11e8-8aac-26234f34fd91.png)

**Comment by PatrickSkowronek** [comment] 2018-04-06 14:08
This is not a bug, it is intended! There is a file size limit(50mb) and a complete zip limit(200mb). But you can cloud please leave a better idea for a better usability.

**Comment by aeimer** [comment] 2018-04-09 21:31
@PatrickSkowronek you can close this issue in my opinion

**Comment by PatrickSkowronek** [comment] 2018-04-10 08:35
@Gargamil thank you for your view on this problem, the main reason is time, to pack the files to a zip. Remember most of the files in the geli are videos. But you can download than the file directly. We should discuss that next meeting.

**Comment by PatrickSkowronek** [comment] 2018-04-21 11:55
@armel22 in this case a yes, but if there more files in the lecture which are possible to download, then it should be possible to select all.

**Closed** 2018-04-25 08:53 UTC
Labels: enhancement, question, web-frontend
