### ISSUE TITLE
Refactor unit location

### ISSUE THREAD

**Issue by grosspersky** [h-da/geli#233] opened 2017-10-19 13:47 UTC
# User Story

### As a: 
developer

### I want:
nice short import paths for the units

### so that:
i don't run into problems with the linter

## Acceptance criteria:
- [ ] unit directory is located directly under /app/webFrontend/src/app/

**Comment by aeimer** [comment] 2017-10-23 14:54
duplicate of #101

**Closed** 2017-10-23 19:38 UTC
Labels: bug, web-frontend
